version: '3.8'

services:
  bot:
    build:
      context: ./grinmorio-BOT
    container_name: bot-service
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_BASE_URL=${API_BASE_URL}
      - CLIENT_ID=${CLIENT_ID}
    volumes:
      - ./grinmorio-BOT:/app
      - bot_node_modules:/app/node_modules
    networks:
      - app-network

  api:
    build:
      context: ./grinmorio-DATABASE
    container_name: grinmorio-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGO_URI=${MONGO_URI}
      - REDIS_URI=${REDIS_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - grinmorio-mongo
      - grinmorio-redis
    volumes:
      - ./grinmorio-DATABASE:/app
      - api_node_modules:/app/node_modules
    networks:
      - app-network
      
  grinmorio-mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    volumes:
      - mongo_data:/data/db
    networks:
      app-network:
        aliases:
          - mongo-db
  grinmorio-redis:
    image: redis:7.0-alpine
    container_name: redis-db
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      app-network:
        aliases:
          - redis-db

volumes:
  bot_node_modules:
  api_node_modules:
  mongo_data:
  redis_data:

networks:
  app-network:
    driver: bridge