services:
  bot:
    build:
      context: ./grinmorio-BOT
    container_name: bot-service
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_BASE_URL=http://api:3000/api
      - CLIENT_ID=${CLIENT_ID}
    volumes:
      - ./grinmorio-BOT:/app
      - bot_node_modules:/app/node_modules
    networks:
      - app-network

volumes:
  bot_node_modules:

networks:
  app-network:
    driver: bridge