services:
  bot:
    build:
      context: ./grinmorio-BOT
    container_name: bot-service
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_BASE_URL=http://api:3000/api
      - CLIENT_ID=${CLIENT_ID}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge